# -*- coding: utf-8 -*-
"""Generated protocol buffer code."""
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_stub.proto
# python -m grpc_tools.protoc -I. test_stub.proto --python_out=. --grpc_python_out=.
#
#    Copyright (C) 2021 Cotopaxi Contributors. All Rights Reserved.
#       Author: Jakub Botwicz
#
#    This file is part of Cotopaxi.
#
#    Cotopaxi is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    Cotopaxi is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Cotopaxi.  If not, see <http://www.gnu.org/licenses/>.
#

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)
# pylint: disable=protected-access
_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="test_stub.proto",
    package="Test_Stub",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0ftest_stub.proto\x12\tTest_Stub"&\n\x0bPingRequest\x12'
    b'\x17\n\x0frequest_message\x18\x01 \x01(\t"(\n\x0cPingResponse'
    b"\x12\x18\n\x10response_message\x18\x01 \x01(\t2I\n\x0cPing_Service"
    b"\x12\x39\n\x04Ping\x12\x16.Test_Stub.PingRequest\x1a\x17.Test_Stub"
    b'.PingResponse"\x00\x62\x06proto3',
)

_PINGREQUEST = _descriptor.Descriptor(
    name="PingRequest",
    full_name="Test_Stub.PingRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="request_message",
            full_name="Test_Stub.PingRequest.request_message",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=30,
    serialized_end=68,
)


_PINGRESPONSE = _descriptor.Descriptor(
    name="PingResponse",
    full_name="Test_Stub.PingResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="response_message",
            full_name="Test_Stub.PingResponse.response_message",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=70,
    serialized_end=110,
)

DESCRIPTOR.message_types_by_name["PingRequest"] = _PINGREQUEST
DESCRIPTOR.message_types_by_name["PingResponse"] = _PINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingRequest = _reflection.GeneratedProtocolMessageType(
    "PingRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _PINGREQUEST,
        "__module__": "test_stub_pb2"
        # @@protoc_insertion_point(class_scope:Test_Stub.PingRequest)
    },
)
_sym_db.RegisterMessage(PingRequest)

PingResponse = _reflection.GeneratedProtocolMessageType(
    "PingResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _PINGRESPONSE,
        "__module__": "test_stub_pb2"
        # @@protoc_insertion_point(class_scope:Test_Stub.PingResponse)
    },
)
_sym_db.RegisterMessage(PingResponse)


_PING_SERVICE = _descriptor.ServiceDescriptor(
    name="Ping_Service",
    full_name="Test_Stub.Ping_Service",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=112,
    serialized_end=185,
    methods=[
        _descriptor.MethodDescriptor(
            name="Ping",
            full_name="Test_Stub.Ping_Service.Ping",
            index=0,
            containing_service=None,
            input_type=_PINGREQUEST,
            output_type=_PINGRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_PING_SERVICE)

DESCRIPTOR.services_by_name["Ping_Service"] = _PING_SERVICE

# @@protoc_insertion_point(module_scope)
